<?php
use Event\Entity\EventEntity;

/* @var $event EventEntity */
?>
<h1>Eventliste</h1>

<table class="table table-bordered">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Beschreibung</th>
        <th>Datum</th>
        <th>Zeit</th>
        <th>Status</th>
        <th>
            <a href="<?php echo $this->url(
                'event-admin/action',
                array('action' => 'create')
            ) ?>" class="btn btn-default">
                anlegen
            </a>

        </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->eventList as $event): ?>
        <tr>
            <td><?php echo $event->getId(); ?></td>
            <td><?php echo $event->getName(); ?></td>
            <td><?php echo $event->getDescription(); ?></td>
            <td><?php echo $this->dateFormat(
                    $event->getDate(), IntlDateFormatter::LONG,
                    IntlDateFormatter::NONE
                ); ?></td>
            <td><?php echo $this->dateFormat(
                    $event->getTime(), IntlDateFormatter::NONE,
                    IntlDateFormatter::SHORT
                ); ?></td>
            <td><?php echo $this->eventStatus($event->getStatus()); ?></td>
            <td>
                <a href="<?php echo $this->url(
                    'event-admin/action',
                    array('action' => 'show', 'id' => $event->getId())
                ) ?>" class="btn btn-default">
                    anzeigen
                </a>
                <a href="<?php echo $this->url(
                    'event-admin/action',
                    array('action' => 'update', 'id' => $event->getId())
                ) ?>" class="btn btn-default">
                    bearbeiten
                </a>
                <a href="<?php echo $this->url(
                    'event-admin/action',
                    array('action' => 'delete', 'id' => $event->getId())
                ) ?>" class="btn btn-default">
                    löschen
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>