<?php
use Event\Entity\EventEntity;

/* @var $event EventEntity */

$event = $this->event;
?>

<h1>Event anzeigen</h1>
<table class="table table-bordered">
    <tbody>
    <tr>
        <th>ID</th>
        <td><?php echo $event->getId(); ?></td>
    </tr>
    <tr>
        <th>Name</th>
        <td><?php echo $event->getName(); ?></td>
    </tr>
    <tr>
        <th>Beschreibug</th>
        <td><?php echo $event->getDescription(); ?></td>
    </tr>
    <tr>
        <th>Datum</th>
        <td><?php echo $this->dateFormat(
                $event->getDate(), IntlDateFormatter::LONG,
                IntlDateFormatter::NONE
            ); ?></td>
    </tr>
    <tr>
        <th>Uhr</th>
        <td><?php echo $this->dateFormat(
                $event->getTime(), IntlDateFormatter::NONE,
                IntlDateFormatter::SHORT
            ); ?></td>
    </tr>
    <tr>
        <th>Status</th>
        <td><?php echo $this->eventStatus($event->getStatus()); ?></td>
    </tr>
    </tbody>
</table>

<hr>
<p>
    <a class="btn btn-default" href="<?php echo $this->url('event-admin'); ?>">
        Liste
    </a>
</p>